# Generated by Django 5.1.2 on 2024-10-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_otps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTPs',
            new_name='Otp',
        ),
    ]
