# Generated by Django 5.1.1 on 2024-10-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_otp_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provideruser',
            name='location',
        ),
    ]
