# Generated by Django 5.1.1 on 2024-10-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_provideruser_city_provideruser_reg_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideruser',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provideruser',
            name='current_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
