# Generated by Django 5.1.1 on 2024-10-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_provideruser_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideruser',
            name='on_duty',
            field=models.BooleanField(default=False),
        ),
    ]
