# Generated by Django 5.1.1 on 2024-10-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_provideruser_on_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumeruser',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provideruser',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
