# Generated by Django 5.1.1 on 2024-10-21 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_consumeruser_device_token_provideruser_device_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('requestActive', models.IntegerField(default=10)),
                ('status', models.CharField(max_length=20)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consumeruser')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.provideruser')),
            ],
        ),
        migrations.AddField(
            model_name='consumeruser',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.task'),
        ),
        migrations.AddField(
            model_name='provideruser',
            name='task_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.task'),
        ),
    ]
