# Generated by Django 5.1.1 on 2024-10-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_task_consumeruser_service_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(default='ambulance', max_length=100),
            preserve_default=False,
        ),
    ]
