# Generated by Django 5.1.1 on 2024-10-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_provideruser_on_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
